GlobalChildProdigyAwards/GCPAWeb

functions/model/Mailer/Templates/payment.html
functions/model/Mailer/Templates/registration.html
functions/model/Mailer/Templates/rejected.html
functions/model/Mailer/Templates/selected.html
functions/model/Mailer/lib.js
functions/model/Mailer/tark/generateTemplate.js
functions/model/Mailer/tark/getTemplate.js

Implemented Mailer mechanism for 
- Registration
- Payment Successful
- Selected
- Rejected

feat(Mailer): Implemented Mailer

---

functions/model/applicant-register/tark/getApplicant.js
src/app/body/common-tools/raw-data-table/raw-data-table.component.ts
src/app/body/common-tools/registration-data-table/registration-data-table.component.ts
src/app/body/common-tools/user-data-table/user-data-table.component.ts
src/app/body/dashboard/edit-registration/edit-registration.component.ts
src/app/body/dashboard/registration-dashboard/registration-dashboard.component.ts
src/app/body/dashboard/registration-details-admin/registration-details-admin.component.ts
src/app/body/dashboard/users-dashboard/users-dashboard.component.ts
src/app/body/number-of-registrations/registration-detail/registration-detail.component.ts
src/app/body/payment/payment.component.ts
src/app/body/registration/registration.component.ts
src/app/header/header.component.html
src/app/header/header.component.ts
src/app/services/activity/activity-service.service.ts
src/app/services/gallery/gallery-dashboard.service.ts
src/app/services/newsroom/news-service.service.ts
src/app/services/partners/partner-service.service.ts
src/app/services/raw-data/raw-data-service.service.ts
src/app/services/register-service/register-service.service.ts
src/app/services/support/support-service.service.ts
src/app/services/testimonials/testimonials-service.service.ts

fixed Raw-Data button, payment amount and logs

fixed rawData and logs

---

functions/model/Mailer/Templates/contactReply.html
functions/model/Mailer/Templates/payment.html
functions/model/Mailer/tark/generateTemplate.js
functions/model/ecommerce/lib.js
functions/model/ecommerce/tark/addOrder.js
functions/model/payment/lib.js
functions/model/payment/payment.js
functions/model/payment/tark/addEcommercePayment.js
functions/model/payment/tark/paymentVerification.js
package-lock.json
package.json
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/body/e-commerce/products/products.component.ts
src/app/body/ecommerce-payment-status/ecommerce-payment-status.component.html
src/app/body/ecommerce-payment-status/ecommerce-payment-status.component.spec.ts
src/app/body/ecommerce-payment-status/ecommerce-payment-status.component.ts
src/app/services/order/order-service.service.ts

Integrated Payment for Ecommerce
Improved Ui for Mails
Integrated Razorpay Payments

feat(Payment): Ecommerce Payment and Mailer fixes

---

.firebaserc
src/app/body/login-page/login-page.component.html
src/app/footer/footer.component.css
src/app/services/auth-service/auth-service.service.ts

fixed email login, resetting of data on google sign in, closing of popup on logging in, reload on logout and footer

Deploy fix 1

---

functions/model/gallery/gallery.js
functions/model/gallery/lib.js
functions/model/gallery/tark/deletePhoto.js
src/app/body/dashboard/gallery-dashboard/gallery-dashboard.component.css
src/app/body/dashboard/gallery-dashboard/gallery-dashboard.component.html
src/app/body/dashboard/gallery-dashboard/gallery-dashboard.component.ts

Implemented Delete Image feature for admin
Implemented Delete Image feature for admin
Delete any uploaded image in the admin panel

feat(Delete Image): delete photos in gallery

---

functions/model/gallery/lib.js
src/app/services/gallery/gallery-dashboard.service.ts

fix(gallery):Fixed the gallery lib

---

src/environments/environment.prod.ts
src/environments/environment.ts

removed recaptcha key from env flies

removed key from env file

---

src/app/body/blog-footer/blog-footer.component.html
src/app/body/blog-header/blog-header.component.html
src/app/body/blog-home/gcpa-book/gcpa-book.component.html
src/app/body/blog-home/podcast/podcast.component.html
src/app/body/blog-home/top-categories/top-categories.component.html
src/app/body/blog-home/video-blogs/video-blogs.component.html
src/app/body/blog/blog.component.html

Fixed blog images and old url dependencies
Changed the endpoint for blogs

fixed blog dependencies to new url

---

src/app/body/payment-status/payment-status.component.html
src/app/body/payment/payment.component.html
src/app/body/payment/payment.component.ts
src/app/body/registration/address-contact/address-contact.component.html
src/app/body/registration/registration.component.html
src/app/header/header.component.html
src/app/services/register-service/register-service.service.ts

added button disable feature to payment and form submission

Fix submit disable

---

functions/model/Mailer/Templates/contact.html
functions/model/Mailer/Templates/contactReply.html
functions/model/Mailer/Templates/payment.html
functions/model/Mailer/Templates/registration.html
functions/model/Mailer/lib.js
functions/model/Mailer/tark/generateTemplate.js
functions/model/support/support.js
functions/model/support/tark/contactUs.js
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/body/amp-redirect/amp-redirect.component.html
src/app/body/amp-redirect/amp-redirect.component.spec.ts
src/app/body/amp-redirect/amp-redirect.component.ts
src/app/body/blog-home/parenting/parenting.component.ts
src/app/body/blog-home/popular/popular.component.ts
src/app/body/blog-home/prodigy-history/prodigy-history.component.ts
src/app/body/category-component/category-component.component.css
src/app/body/category-component/category-component.component.html
src/app/body/category-component/category-component.component.spec.ts
src/app/body/category-component/category-component.component.ts
src/app/body/contact/contact.component.html
src/app/body/contact/contact.component.ts
src/app/body/registration/registration.component.html
src/app/body/tag/tag.component.css
src/app/body/tag/tag.component.html
src/app/body/tag/tag.component.spec.ts
src/app/body/tag/tag.component.ts
src/app/services/wp-service/wp-service.service.ts

Fixed the Contact us section
Fixed the blog routes
Fixed the AMP and Feed redirects
fixed the Tag handling 
Stopped registrations

fix(gallery):Fixed contact us and blog routes

---

functions/model/testimonial/lib.js
functions/model/testimonial/tark/deleteTestimonial.js
functions/model/testimonial/tark/editTestimonial.js
functions/model/testimonial/testimonial.js
src/app/body/dashboard/testimonials-dashboard/testimonials-dashboard.component.css
src/app/body/dashboard/testimonials-dashboard/testimonials-dashboard.component.html
src/app/body/dashboard/testimonials-dashboard/testimonials-dashboard.component.ts
src/app/body/testimonial/testimonial.component.html

Added edit and delete functionality in Testimonials

feat(testimonial):edit and delete functionality

---

functions/model/applicant-register/lib.js
functions/model/applicant-register/tark/applicant-register.js
src/app/Interfaces/RegistrationInterface.ts
src/app/body/registration/registration.component.html
src/app/body/registration/registration.component.ts
src/app/services/register-service/register-service.service.ts

added receive updates through emails checkbox field.

Email updates

---

functions/model/raw-data/lib.js
functions/model/raw-data/raw-data.js
functions/model/raw-data/tark/getRawData.js

fix-function-names

---

functions/model/gallery/lib.js
functions/model/newsroom/lib.js
functions/model/partner/lib.js
src/app/body/gallery/gallery.component.html
src/app/body/newsroom/newsroom.component.html
src/app/body/partners/partners.component.html

Ordered the Partners logo
By Adding images in the partners section

PartnersLogo : Ordered the logos 

---

src/app/body/gallery/gallery.component.html
src/app/body/gallery/gallery.component.ts
src/app/header/header.component.ts
src/app/services/gallery/gallery-dashboard.service.ts
src/app/services/start-serice.service.spec.ts
src/app/services/start-serice.service.ts

Added Start service to load gallery images on application load

fix(gallery):fixed the gallery

---

src/app/body/registration/registration.component.html

Fixed admin only access to Registration page

fix(register):Fixed admin only acccess

---

functions/model/Mailer/Templates/payment.html
functions/model/Mailer/Templates/registration.html
functions/model/Mailer/tark/getTemplate.js

Fixed the mailer template location

Fixed mailer template location

---

src/app/body/dashboard/edit-registration/edit-registration.component.html
src/app/body/dashboard/edit-registration/edit-registration.component.ts
src/app/body/dashboard/registration-details-admin/registration-details-admin.component.html
src/app/body/number-of-registrations/registration-detail/registration-detail.component.html
src/app/body/registration/category-upload/category-upload.component.html

fixes:
registration details files display
social media category display
spacing in registration form

fix registration details

---

functions/model/applicant-register/tark/applicant-register.js
functions/model/ecommerce/lib.js
functions/model/ecommerce/products.js
functions/model/ecommerce/tark/deleteProduct.js
functions/model/ecommerce/tark/editProduct.js
functions/model/gallery/lib.js
functions/model/newsroom/lib.js
functions/model/partner/lib.js
functions/model/payment/lib.js
functions/model/support/tark/contactUs.js
src/app/body/common-tools/product-data-table/product-data-table.component.html
src/app/body/common-tools/product-data-table/product-data-table.component.ts
src/app/body/dashboard/gallery-dashboard/gallery-dashboard.component.html

Added edit and delete functionality in Ecommerce admin dashboard

editDelete-ecommerce

---

src/app/body/number-of-registrations/registration-detail/registration-detail.component.html
src/app/body/number-of-registrations/registration-detail/registration-detail.component.ts

integrated new popup in registration details

fix popup user side

---

functions/model/mailer/templates/PaymentPending.html
functions/model/mailer/templates/PaymentSuccess.html
functions/model/mailer/templates/regSuccess.html
src/app/body/contact/contact.component.html
src/app/body/payment-status/payment-status.component.css
src/app/body/payment-status/payment-status.component.html
src/app/body/payment/payment.component.html
src/app/body/registration/registration.component.html
src/app/footer/footer.component.html

fixed mail
fixed payment status ui
fixed payment ui

Changes done

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/body/dashboard/newsroom-dashboard/newsroom-dashboard.component.html
src/app/body/dashboard/newsroom-dashboard/newsroom-dashboard.component.ts
src/app/body/dashboard/sponsors-partners/sponsors-partners.component.css
src/app/body/dashboard/sponsors-partners/sponsors-partners.component.html
src/app/body/dashboard/sponsors-partners/sponsors-partners.component.ts
src/app/body/dashboard/testimonials-dashboard/testimonials-dashboard.component.css
src/app/body/dashboard/testimonials-dashboard/testimonials-dashboard.component.html
src/app/body/dashboard/testimonials-dashboard/testimonials-dashboard.component.ts
src/app/body/faq/faq.component.css
src/app/body/faq/faq.component.html
src/app/body/faq/faq.component.spec.ts
src/app/body/faq/faq.component.ts
src/app/body/privacy-policy/privacy-policy.component.html
src/app/body/privacy-policy/privacy-policy.component.spec.ts
src/app/body/privacy-policy/privacy-policy.component.ts
src/app/footer/footer.component.css
src/app/footer/footer.component.html
src/app/services/newsroom/news-service.service.ts
src/app/services/partners/partner-service.service.ts
src/app/services/testimonials/testimonials-service.service.ts

added new popup in admin side,
added privacy policy and faq

Fix popup admin

---

functions/model/raw-data/tark/updateRawData.js
functions/model/support/lib.js
functions/model/support/support.js
functions/model/support/tark/getAllSupport.js
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/body/dashboard/dashboard.component.html
src/app/body/dashboard/dashboard.component.ts
src/app/body/dashboard/support-admin/support-admin.component.html
src/app/body/dashboard/support-admin/support-admin.component.spec.ts
src/app/body/dashboard/support-admin/support-admin.component.ts
src/app/body/dashboard/support-admin/support-details-admin/support-details-admin.component.css
src/app/body/dashboard/support-admin/support-details-admin/support-details-admin.component.html
src/app/body/dashboard/support-admin/support-details-admin/support-details-admin.component.spec.ts
src/app/body/dashboard/support-admin/support-details-admin/support-details-admin.component.ts
src/app/services/activity/activity-service.service.ts
src/app/services/support/support-service.service.ts

Added support chat feature in the admin side

feature-support-adminSide

---

functions/model/mailer/tark/generateTemplate.js
functions/model/mailer/templates/newMessage.html
functions/model/mailer/templates/supportTicket.html
functions/model/support/support.js
functions/model/support/tark/createNewSupport.js
functions/model/support/tark/sendSupportMail.js
src/app/body/blog-header/blog-header.component.html
src/app/body/dashboard/support-admin/support-details-admin/support-details-admin.component.html
src/app/body/dashboard/support-admin/support-details-admin/support-details-admin.component.ts
src/app/body/home/home.component.html
src/app/body/home/testimonials/section4/section4.component.css
src/app/body/home/testimonials/sections/sections.component.css
src/app/body/home/testimonials/sections2/sections2.component.css
src/app/body/home/testimonials/sections3/sections3.component.css
src/app/body/home/testimonials/testimonials.component.ts
src/app/body/login-page/login-page.component.css
src/app/body/login-page/login-page.component.html
src/app/body/registration/address-contact/address-contact.component.html
src/app/body/registration/category-upload/category-upload.component.html
src/app/body/registration/personal-details/personal-details.component.html
src/app/body/registration/registration.component.html
src/app/services/support/support-service.service.ts

Added Mailer to Support Chat
Fixed UI of login , home page
Added Mailer to Support Chat
Fixed UI of login , home page

fix(mailer, Ui): Added Mailer to Support chat,Fixed ui

---

src/app/body/dashboard/edit-registration/edit-registration.component.html
src/app/body/dashboard/edit-registration/edit-registration.component.ts
src/app/body/dashboard/newsroom-dashboard/newsroom-dashboard.component.html
src/app/body/dashboard/newsroom-dashboard/newsroom-dashboard.component.ts
src/app/body/dashboard/registration-details-admin/registration-details-admin.component.html
src/app/body/home/featured-in/featured-in.component.html
src/app/body/home/featured-in/featured-in.component.ts
src/app/body/home/home.component.ts
src/app/body/number-of-registrations/registration-detail/registration-detail.component.html
src/app/body/number-of-registrations/registration-detail/registration-detail.component.ts

fixed registration details issues in admin side, and video link upload

fixed registration details issues

---

functions/model/payment/tark/addPayment.js
src/app/body/payment/payment.component.html
src/app/body/payment/payment.component.ts
src/app/body/registration/registration.component.html

Changed the Payment for India as 1300 INR and  for other as 15 USD.
Changed the Payment for India as 1300 INR and  for other as 15 USD.

fix(popup): Separate Amounts for India and Others

---

functions/model/mailer/tark/generateTemplate.js
functions/model/mailer/templates/regSuccess.html
src/app/app.component.html
src/app/body/blog-footer/blog-footer.component.css
src/app/body/blog-footer/blog-footer.component.html
src/app/body/common-tools/data-table/data-table.component.css
src/app/body/common-tools/data-table/data-table.component.html
src/app/body/common-tools/support-data-table/support-data-table.component.css
src/app/body/common-tools/support-data-table/support-data-table.component.html
src/app/body/number-of-registrations/number-of-registrations.component.html
src/app/body/number-of-registrations/registration-detail/registration-detail.component.html
src/app/body/number-of-registrations/registration-detail/registration-detail.component.ts
src/app/body/support/support-details/support-details.component.css
src/app/body/support/support-details/support-details.component.html
src/app/body/support/support-popup/support-popup.component.ts
src/app/body/support/support.component.html
src/app/header/header.component.css
src/app/header/header.component.html
src/app/header/user-card/user-card.component.html
src/app/services/support/support-service.service.ts

- Fixed content in emails
- Fixed the support ticket
- Improved the Ui of Registeration table
- Changed the footer

Fix: Email Template & Support Ticket

---

angular.json
src/app/services/start-serice.service.ts
src/robots.txt
src/sitemap.xml

- Added Sitemap for better SEO
- Started `getAllPosts()` method in startservice for faster loading.

fix(popup):added sitemap

---

src/app/body/blog-footer/blog-footer.component.html
src/app/body/privacy-policy/privacy-policy.component.css
src/app/body/privacy-policy/privacy-policy.component.html
src/app/body/terms-condi/terms-condi.component.css
src/app/body/terms-condi/terms-condi.component.html

- Updated the New content for the privacy policy page

feat(privacy-policy) -  New Content
